- hosts: localhost
  gather_facts: no
  vars:
    config: '{{  ovconfig_file }}'
    server_hardware_type_name: " SY480G10 M1:416SA M3:4820CNA"
    enclosure_group_name: "3 Frame VC-ETH SAS-Switch"
    auto_assign_server_hardware: "False"
    
  tasks:
    - set_fact: osflavor=ESXIBOOT osbase=ESXIBASE ov_template=ANSIBLE_OS_Deploy_via_iLO install=http://osdepl.demo.local/esx7/esx7custom.iso source=ksesx.cfg.j2 destination=/persistent/osdepl/esx7/ks_custom7.cfg
      when: (osflavor == "1- OS_ESXI")

    - set_fact: osflavor=LINUXBOOT2 osbase=LINUXBOOT ov_template=ANSIBLE_OS_Deploy_via_iLO install=http://osdepl.demo.local/rhel77/rhel77custom.iso source=ksrhel.cfg.k2 destination=/persistent/osdepl/rhel77/rhel77ks.cfg
      when: (osflavor == "2- OS_RHEL")

    - set_fact: osflavor=LINUXBOOT3 osbase=LINUXBOOT ov_template=ANSIBLE_OS_Deploy_via_iLO install=http://osdepl.demo.local/centos/centos7custom.iso source=kscentos.cfg.k2 destination=/persistent/osdepl/centos/centos7ks.cfg
      when: (osflavor == "3- OS_CentOS with Docker")
      
    - set_fact: osflavor=LINUXBOOT4 osbase=LINUXBOOT ov_template=ANSIBLE_OS_Deploy_via_iLO install=http://osdepl.demo.local/rocky/Rocky84_kickstart-efi.iso source=ksrocky.cfg.j2 destination=/persistent/osdepl/rocky/rockyks.cfg
      when: (osflavor == "4- OS_Rocky8.4 with Docker")  

    - debug: var=ipaddr
    - debug: var=osbase
    - debug: var=hostn
    - debug: var=ilo_username

    - name: Sleep for 300 seconds and continue with play
      wait_for:
        timeout: 300
      delegate_to: localhost

    - name: Install pip module hpOneView
      pip:
        name: hpOneView
        umask: "0022"
        extra_args: "--user"
        state: present

#   - name: Install pip module hpICsp
#     pip:
#       name: hpICsp
#       umask: "0022"
#       extra_args: "--user"
#       state: present

    - name: Install pip module python-hpilo
      pip:
        name: python-hpilo
        umask: "0022"
        extra_args: "--user"
        state: present

    - name: create custom kickstart file
      template:
        src: "{{source}}"
        dest:  "{{destination}}"
      delegate_to: localhost

    - name : "Create Server Profile from Template - {{ profile_name }}"
      hpe.oneview.oneview_server_profile:
        config: "{{ config }}"
        data:
          name: "{{ profile_name }}"
          serverProfileTemplateName: "{{ ov_template }}"
          serverHardwareName:         "{{ ov_server }}"
        params:
          force: True
      register: mpHostInfo
      delegate_to: localhost
    - debug:
        var:  server_hardware.mpHostInfo.mpIpAddresses[1].address 

    - name: Task to boot a system using an ISO from an HP iLO interface only if the system is an HP server
      community.general.hpilo_boot:
        host: "{{ server_hardware.mpHostInfo.mpIpAddresses[1].address }}" 
        login: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
        media: cdrom
        image: "{{ install }}" 
      delegate_to: localhost

    - name: wait for port 22 to become active
      wait_for:
        host: "{{ipaddr}}"
        port: 22
        delay: 20
        state: started
        timeout: 1600
      delegate_to: localhost
      
#    - name: Install pip module docker for next task
#      remote_user: vagrant
#      become: yes
#      become_method: sudo
#      pip:
#        name: docker
#        umask: "0022"
#        state: present    
#      delegate_to: "{{ ipaddr }}"
#      when: (osflavor == "3- OS_CentOS with Docker") or (osflavor == "4- OS_Rocky with Docker")

#   - name: Install Nginx
#     remote_user: vagrant
#     become: yes
#     become_method: sudo
#     community.general.docker_container:
#       name: nginx
#       image: nginx:latest
#       detach: True
#       ports:
#           - 80:80
#     delegate_to: "{{ ipaddr }}"
#     when: (osflavor == "3- OS_CentOS with Docker") or (osflavor == "4- OS_Rocky with Docker")

#   - name: Tweak Nginx
#     remote_user: vagrant
#     become: yes
#     become_method: sudo
#     command:  docker exec -it nginx sed -i 's/nginx/the HPE Meeting/g' /usr/share/nginx/html/index.html
#     delegate_to: "{{ ipaddr }}"
#     when: (osflavor == "3- OS_CentOS with Docker") or (osflavor == "4- OS_Rocky with Docker")
      
    - name: Add ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        datacenter_name: ctcbbn
        cluster_name: Democluster
        esxi_hostname: '{{ ipaddr }}'
        esxi_username: 'root'
        esxi_password: 'HP1nvent!'
        state: present
        validate_certs: False
      delegate_to: localhost
      when: (osbase == "ESXIBASE")
